branch-defaults:
  master:
    environment: microprofile-io-env
deploy:
  artifact: target/${project.artifactId}-${project.version}-ebs-zip.zip
global:
  application_name: microprofile.io-application
  default_ec2_keyname: microprofile-key-pair
  default_platform: Java 8
  default_region: us-west-2
  profile: null
  sc: git
